### PR TITLE
Change to new version.

### PR DESCRIPTION
**Pull request by frozyeah**
Just change some symbols.

### CODE REVIEW

**Comment by vasilysinitsin** [comment]
Hello, Kirill.
Spasibo for your PR.
I am now very limited in internet access and workstation as well, so I am only making assumptions by viewing the TravisCI build log.
Looks like `filters` keyword is either no more present in FaceApp response or renamed making tests to fail fetching list of filters. Could you please check those.
If so — the only visible solution to me is making a manual list of avaliable filters like that was in early commits.

**Comment by frozyeah** [comment]
Hello, you have no reference to the documentation? I have not found any articles on the web.

**Comment by vasilysinitsin** [comment]
Kirill, unfortunately API is not documented hence it's necessary to observe the json response manually.

**Comment by vasilysinitsin** [comment]
Could you just confirm if the original repo is broken now and your repo in working condition not considering the tests? I am far away from shore on satellite internet and can only merge from web in case current repo does not work at all.
Thanks a lot.

**Comment by Tirael666** [comment]
@frozyeah As I see from today the library from your repo shows "Please Update. You are running an old version" message again. I tried to experiment with BASE_API_URL and BASE_HEADERS params, but without any luck. :(

**Comment by frozyeah** [comment]
@Tirael666 Yes, in my project this banner too, I don't have enough time for check this problem. I'm trying to fix it, but for this API there is no documentation.

**Pull request closed without merging**
